//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edomozh.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Queries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Queries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Edomozh.Properties.Queries", typeof(Queries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table if not exists &quot;User&quot; (
        /// &quot;Id&quot;         integer not null primary key,
        /// &quot;FirstName&quot;  text,
        /// &quot;LastName&quot;   text,
        /// &quot;Username&quot;   text
        ///);
        ///
        ///create table if not exists &quot;Entry&quot; (
        /// &quot;UserId&quot;    integer not null,
        /// 
        /// &quot;Year&quot;      integer not null,
        /// &quot;Month&quot;     integer not null,
        /// &quot;Day&quot;       integer not null,
        /// 
        /// &quot;Status&quot;    text,
        ///
        /// primary key (&quot;UserId&quot;, &quot;Year&quot;, &quot;Month&quot;, &quot;Day&quot;),
        /// foreign key (&quot;UserId&quot;) references &quot;User&quot; (&quot;Id&quot;) 
        ///);.
        /// </summary>
        internal static string CreateTables {
            get {
                return ResourceManager.GetString("CreateTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into Entry (UserId, Year, Month, Day, Status) 
        ///values (@UserId, @Year, @Month, @Day, @Status).
        /// </summary>
        internal static string Entry_Insert {
            get {
                return ResourceManager.GetString("Entry_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * 
        ///from Entry 
        ///where UserId = @UserId.
        /// </summary>
        internal static string Entry_Select {
            get {
                return ResourceManager.GetString("Entry_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into User (Id, FirstName, LastName, Username) 
        ///values (@Id, @FirstName, @LastName, @Username).
        /// </summary>
        internal static string User_Insert {
            get {
                return ResourceManager.GetString("User_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * 
        ///from User
        ///where Id = @Id.
        /// </summary>
        internal static string User_Select {
            get {
                return ResourceManager.GetString("User_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update User
        ///set FirstName = @FirstName, 
        ///    LastName  = @LastName, 
        ///    Username  = @Username
        ///where Id = @Id.
        /// </summary>
        internal static string User_Update {
            get {
                return ResourceManager.GetString("User_Update", resourceCulture);
            }
        }
    }
}
